# -*- coding: utf-8 -*-
"""Project2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oCi_1f892WxDE8RAm2W27h9OWkDNWzlx
"""

## Project2
 # Reg_no: 075

#importing libabries
import pandas as pd
import numpy as np

data = pd.read_csv('https://raw.githubusercontent.com/Tiamiyu1/Python-for-Data-Science-and-Analytics/main/Data/store_data.csv')

data

data.tail(4)

data.tail(4).sum()

# storeA has the highest total sales from the final month of data.

data.describe().T

#storeB has the average data.

## Number  3
data[data['week'] == '2016-03-13']

# StoreD sold the most on this week



data.min()

# StoreC made the worst sale of 927 in  the second week of may 2014 (2014-05-04)

data.tail(3).max()

# StoreA had the most sales.

